name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      dotnet-logging:
        required: true
        type: choice
        default: minimal
        options:
          - quiet
          - minimal
          - normal
          - detailed
          - diagnostic

permissions:
  actions: read
  contents: write
  pull-requests: write
  security-events: write

jobs:
  all:
    if: github.run_id != 1
    name: Build & Tests
    uses: dailydevops/pipelines/.github/workflows/build-dotnet-single.yml@1acd2ca40debe423847625cdb537f5cee3b14b43 # 2.5.1
    with:
      dotnetLogging: ${{ inputs.dotnet-logging || 'minimal' }}
      dotnetVersion: ${{ vars.NE_DOTNET_TARGETFRAMEWORKS }}
      solution: ./FluentValue.slnx
    secrets: inherit
